(ns magic.drift
  "The drift check and its dll-sources.edn manifest: the SHA256 of the .clj
   source behind each committed reference DLL, re-recorded by refresh-stdlib /
   bootstrap. check-drift fails when a checked path differs from HEAD, meaning
   a source was edited without refreshing its DLL. This namespace also stamps
   the DLL mtimes from that manifest: a source that still hashes gets its DLL
   stamped newer, so the loader takes the committed bytes over recompiling."
  (:require [babashka.fs :as fs]
            [babashka.tasks :refer [shell]]
            [clojure.edn]
            [clojure.string :as str]
            [magic.log :as log])
  (:import [java.security MessageDigest]))

(def manifest-path "magic-compiler/dll-sources.edn")

(def ^:private references-dir "nostrand/references")

;; Ordered: stdlib sources shadow nothing, but clojure.* lives under stdlib
;; while magic.* lives under src and mage under its own tree. A DLL whose
;; namespace resolves in none of these (the vendored clojure.tools.analyzer.*)
;; has no in-tree source and is skipped.
(def ^:private source-roots
  ["magic-compiler/src/stdlib" "magic-compiler/src" "mage/src"])

(defn- sha256 [file]
  (let [md (MessageDigest/getInstance "SHA-256")]
    (apply str (map #(format "%02x" (bit-and % 0xff))
                    (.digest md (fs/read-all-bytes file))))))

(defn- ns->source
  "Resolve a committed DLL's namespace (munged form, dots to slashes) to its
   source file, or nil when there is no in-tree source."
  [ns-munged]
  (let [rel (str/replace ns-munged "." "/")]
    (some (fn [root]
            (some (fn [ext]
                    (let [f (fs/file root (str rel ext))]
                      (when (fs/exists? f) (str f))))
                  [".clj" ".cljc"]))
          source-roots)))

(def ^:private dll-dirs
  [references-dir
   "magic-unity/Runtime/magic"
   "nostrand/bin/Release/net471"])

(defn touch-dlls!
  "clojure.core/load-one picks between a .clj source and its .clj.dll by
   comparing mtimes, and a fresh checkout leaves those arbitrary. Give every
   committed DLL a deliberate mtime instead: 1s newer than its source when
   the source still hashes to its manifest entry, so requires load the DLL;
   1s older when the source was edited, so the build recompiles it; now when
   it has no in-tree source."
  []
  (let [now      (java.time.Instant/now)
        recorded (try (clojure.edn/read-string (slurp manifest-path))
                      (catch Exception _ {}))]
    (doseq [dir dll-dirs
            :when (fs/exists? dir)
            dll (fs/glob dir "*.clj.dll")
            :let [nsm (str/replace (str (fs/file-name dll)) #"\.clj\.dll$" "")
                  src (ns->source nsm)]]
      (fs/set-last-modified-time
       dll
       (cond
         (nil? src) now
         (= (sha256 src) (:sha256 (get recorded (symbol nsm))))
         (.plusSeconds (.toInstant (fs/last-modified-time src)) 1)
         :else
         (.minusSeconds (.toInstant (fs/last-modified-time src)) 1))))))

(defn record!
  "Rewrite the manifest from the current sources."
  []
  (let [entries (into (sorted-map)
                      (keep (fn [dll]
                              (let [nsm (str/replace (str (fs/file-name dll))
                                                     #"\.clj\.dll$" "")]
                                (when-let [src (ns->source nsm)]
                                  [(symbol nsm) {:source src
                                                 :sha256 (sha256 src)}]))))
                      (fs/glob references-dir "*.clj.dll"))]
    (spit manifest-path
          (str ";; Auto-generated by magic.drift/record! (bb refresh-stdlib /\n"
               ";; bb bootstrap). DO NOT EDIT BY HAND.\n"
               ";; SHA256 of the .clj source each committed .clj.dll was last refreshed\n"
               ";; from. bb check-drift re-records this file and fails if a source\n"
               ";; changed without its DLL being refreshed and committed.\n"
               "{\n"
               (str/join "\n"
                         (for [[k v] entries]
                           (format " %s {:source %s, :sha256 %s}"
                                   k (pr-str (:source v)) (pr-str (:sha256 v)))))
               "}\n"))
    (println "recorded" manifest-path "-" (count entries) "sources")))

(defn check!
  "After the regen tasks have run, fail if any checked path differs from HEAD.
   Committed DLLs are byte-diffed, except magic-unity's MAGIC Clojure.dll and
   Magic.Runtime.dll: they embed a git-describe SourceRevisionId, so they are
   restored from HEAD instead."
  []
  (let [checked-paths ["magic-runtime/Magic.Runtime/Generated"
                       manifest-path
                       "magic-unity/package.json"
                       "magic-unity/Runtime/clojure-clr"
                       "nostrand/references"
                       "magic-unity/Runtime/magic"]
        _ (shell "git" "checkout" "--"
                 "magic-unity/Runtime/magic/Clojure.dll"
                 "magic-unity/Runtime/magic/Magic.Runtime.dll")
        {:keys [out]} (apply shell {:continue true :out :string}
                             "git" "status" "--porcelain" "--" checked-paths)]
    (when-not (str/blank? out)
      (apply log/fail! "drift detected"
             (concat [""
                      "Drift detected: a generated file or committed DLL is stale."
                      "The working tree now holds the refreshed version of each path below."
                      "Commit them if the drift is expected (chore(bootstrap): refresh ...);"
                      "investigate before reverting if not."
                      ""]
                     (take 80 (str/split-lines out)))))))
