(ns magic.drift
  "The drift check and its dll-sources.edn manifest: the SHA256 of the .clj
   source behind each committed reference DLL, re-recorded by refresh-stdlib,
   refresh-nostrand and bootstrap. check-drift fails when a checked path
   differs from HEAD, meaning a source was edited without refreshing its DLL.
   This namespace also stamps the DLL mtimes from that manifest: a source that
   still hashes gets its DLL stamped newer, so the loader takes the committed
   bytes over recompiling.
   It also verifies the committed copies of one file that the repo keeps in
   several trees, and the partition of the reference DLLs across the package's
   two shipped sets."
  (:require [babashka.fs :as fs]
            [clojure.set]
            [babashka.tasks :refer [shell]]
            [clojure.edn]
            [clojure.string :as str]
            [magic.log :as log]
            [magic.unity :as unity])
  (:import [java.security MessageDigest]))

(def manifest-path "magic-compiler/dll-sources.edn")

(def ^:private references-dir "nostrand/references")

;; The vendored clojure.tools.analyzer.* DLLs resolve in none of these: they
;; are the only committed DLLs with no in-tree source.
(def ^:private source-roots
  ["magic-compiler/src/stdlib" "magic-compiler/src" "mage/src" "nostrand"])

(defn- sha256 [file]
  (let [md (MessageDigest/getInstance "SHA-256")]
    (apply str (map #(format "%02x" (bit-and % 0xff))
                    (.digest md (fs/read-all-bytes file))))))

(defn- ns->source
  "Resolve a committed DLL's namespace (munged form, dots to slashes) to its
   source file, or nil when there is no in-tree source."
  [ns-munged]
  (let [rel (str/replace ns-munged "." "/")]
    (some (fn [root]
            (some (fn [ext]
                    (let [f (fs/file root (str rel ext))]
                      (when (fs/exists? f) (str f))))
                  [".clj" ".cljc"]))
          source-roots)))

(def ^:private stdlib-dir "magic-unity/Runtime/magic")

(def ^:private compiler-dir "magic-unity/Editor/Compiler")

(def ^:private dll-dirs
  [references-dir
   stdlib-dir
   compiler-dir
   "nostrand/bin/Release/net471"])

(defn touch-dlls!
  "clojure.core/load-one picks between a .clj source and its .clj.dll by
   comparing mtimes, and a fresh checkout leaves those arbitrary. Give every
   committed DLL a deliberate mtime instead: 1s newer than its source when
   the source still hashes to its manifest entry, so requires load the DLL;
   1s older when the source was edited, so the build recompiles it; now when
   it has no in-tree source."
  []
  (let [now      (java.time.Instant/now)
        recorded (try (clojure.edn/read-string (slurp manifest-path))
                      (catch Exception _ {}))]
    (doseq [dir dll-dirs
            :when (fs/exists? dir)
            dll (fs/glob dir "*.clj.dll")
            :let [nsm (str/replace (str (fs/file-name dll)) #"\.clj\.dll$" "")
                  src (ns->source nsm)]]
      (fs/set-last-modified-time
       dll
       (cond
         (nil? src) now
         (= (sha256 src) (:sha256 (get recorded (symbol nsm))))
         (.plusSeconds (.toInstant (fs/last-modified-time src)) 1)
         :else
         (.minusSeconds (.toInstant (fs/last-modified-time src)) 1))))))

(defn record!
  "Rewrite the manifest from the current sources."
  []
  (let [entries (into (sorted-map)
                      (keep (fn [dll]
                              (let [nsm (str/replace (str (fs/file-name dll))
                                                     #"\.clj\.dll$" "")]
                                (when-let [src (ns->source nsm)]
                                  [(symbol nsm) {:source src
                                                 :sha256 (sha256 src)}]))))
                      (fs/glob references-dir "*.clj.dll"))]
    (spit manifest-path
          (str ";; Auto-generated by magic.drift/record! (bb refresh-stdlib /\n"
               ";; bb refresh-nostrand / bb bootstrap). DO NOT EDIT BY HAND.\n"
               ";; SHA256 of the .clj source each committed .clj.dll was last refreshed\n"
               ";; from. bb check-drift re-records this file and fails if a source\n"
               ";; changed without its DLL being refreshed and committed.\n"
               "{\n"
               (str/join "\n"
                         (for [[k v] entries]
                           (format " %s {:source %s, :sha256 %s}"
                                   k (pr-str (:source v)) (pr-str (:sha256 v)))))
               "}\n"))
    (println "recorded" manifest-path "-" (count entries) "sources")))

(def ^:private committed-copies
  "Files the repo commits in several trees, which must stay byte-identical.
   Each Unity project needs the assembly inside its own Assets/, and the smoke
   project also commits it as csharp-lib source and as :csharp-out output."
  {"smoke_csharp.dll"
   ["unity-examples/magic-unity-smoke/csharp-lib/src_classes/smoke_csharp.dll"
    "unity-examples/magic-unity-smoke/Assets/Plugins/CSharp/smoke_csharp.dll"
    "unity-examples/magic-unity-coexist/Assets/Plugins/Consumer/smoke_csharp.dll"]})

(defn- copy-divergences []
  (for [[file-name paths] committed-copies
        :when (next (distinct (map sha256 paths)))]
    (str "  " file-name "\n"
         (str/join "\n" (for [p paths] (str "    " (subs (sha256 p) 0 12) "  " p))))))

(defn check-copies!
  "Fail if the copies of one committed file have drifted apart."
  []
  (when-let [diverged (seq (copy-divergences))]
    (apply log/fail! "committed copies diverged"
           (concat ["" "Rebuild wrote one copy and not the others:" ""] diverged)))
  (println "committed copies OK -" (count committed-copies) "file(s)"))

(defn- clj-assemblies
  "The Clojure assembly file names in a directory. Only the clj-extensions:
   the same directories also hold hand-written C# assemblies (Clojure.dll,
   Magic.Runtime.dll, Nostrand.dll), which are in no reference set."
  [dir]
  (into (sorted-set)
        (comp (map #(str (fs/file-name %)))
              (filter (fn [n] (some #(str/ends-with? n %) unity/clj-extensions))))
        (fs/glob dir "*.dll")))

(def ^:private editor-excluded
  "Reference DLLs the package deliberately ships in neither set. Must agree
   with editor-excluded in magic-compiler/refresh.clj, which does the deploy."
  #{"nostrand.repl.clj.dll"})

(defn check-partition!
  "Fail unless Runtime/magic and Editor/Compiler partition nostrand/references,
   less editor-excluded. A DLL missing from a set is an absence, which git
   status cannot report. Blind to a stale leftover: both deploys are copies
   that never delete, so a renamed namespace keeps its old DLL in every set
   and stays a valid partition."
  []
  (let [refs     (clojure.set/difference (clj-assemblies references-dir) editor-excluded)
        stdlib   (clj-assemblies stdlib-dir)
        compiler (clj-assemblies compiler-dir)
        both     (clojure.set/intersection stdlib compiler)
        missing  (clojure.set/difference refs (clojure.set/union stdlib compiler))
        extra    (clojure.set/difference (clojure.set/union stdlib compiler) refs)]
    (when (or (seq both) (seq missing) (seq extra))
      (apply log/fail! "reference DLLs are not partitioned"
             (concat
              [""
               (str "Every DLL in " references-dir " (" (count refs) ", less "
                    (str/join ", " (sort editor-excluded)) ") must ship in exactly"
                    " one package set: " stdlib-dir " (" (count stdlib) ", players included)"
                    " or " compiler-dir " (" (count compiler) ", Editor-only).")
               ""]
              (when (seq both)
                (cons "In both package sets:" (map #(str "  " %) both)))
              (when (seq missing)
                (cons "In references but shipped by neither set:"
                      (map #(str "  " %) missing)))
              (when (seq extra)
                (cons "Shipped by the package but not in references:"
                      (map #(str "  " %) extra))))))
    (println "reference DLL partition OK -" (count stdlib) "stdlib +"
             (count compiler) "compiler =" (count refs))))

(defn check!
  "After the regen tasks have run, fail if any checked path differs from HEAD.
   Committed DLLs are byte-diffed, except magic-unity's MAGIC Clojure.dll and
   Magic.Runtime.dll: they embed a git-describe SourceRevisionId, so they are
   restored from HEAD instead."
  []
  (let [checked-paths ["magic-runtime/Magic.Runtime/Generated"
                       manifest-path
                       "magic-unity/package.json"
                       "magic-unity/Runtime/clojure-clr"
                       "nostrand/references"
                       "magic-unity/Runtime/magic"
                       "magic-unity/Editor/Compiler"]
        _ (shell "git" "checkout" "--"
                 "magic-unity/Runtime/magic/Clojure.dll"
                 "magic-unity/Runtime/magic/Magic.Runtime.dll")
        {:keys [out]} (apply shell {:continue true :out :string}
                             "git" "status" "--porcelain" "--" checked-paths)]
    (when-not (str/blank? out)
      (apply log/fail! "drift detected"
             (concat [""
                      "Drift detected: a generated file or committed DLL is stale."
                      "The working tree now holds the refreshed version of each path below."
                      "Commit them if the drift is expected (chore(bootstrap): refresh ...);"
                      "investigate before reverting if not."
                      ""]
                     (take 80 (str/split-lines out)))))))
