name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Get current branch name
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    # Setup .Net
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Checkout github repos
    - name: Checkout Clojure.Runtime
      uses: actions/checkout@v2
      with:
        repository: nasser/Clojure.Runtime
        path: ./Clojure.Runtime

    - name: Checkout Nostrand
      uses: actions/checkout@v2
      with:
        repository: nasser/nostrand
        path: ./nostrand

    - name: Checkout Magic
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_NAME }}
        path: ./magic

    # Build Clojure.Runtime
    - name: Generate Clojure.Runtime assemblies
      run: |
        cd Clojure.Runtime/
        dotnet build

    # Build Clojure.Runtime inside magic folder
    - name: Generate Clojure.Runtime assemblies of magic
      run: |
        cd magic/Magic.Runtime/
        dotnet build

    # Copy Magic dll of current branch to nostrand
    - name: Copy current Magic bootstrap dlls to nostrand references
      run: |
        if [ -d "/magic/bootstrap" ] 
        then
        cp magic/bootstrap/* nostrand/references/
        fi
        cp Clojure.Runtime/bin/Debug/netstandard2.0/* nostrand/references-netstandard/
        cp Clojure.Runtime/bin/Debug/net40/* nostrand/references-net4x/
        cp magic/Magic.Runtime/bin/Debug/netstandard2.0/* nostrand/references-netstandard/
        cp magic/Magic.Runtime/bin/Debug/net461/* nostrand/references-net4x/

    # Build Nostrand using the previously copied dll
    - name: Build Nostrand
      run: |
        cd nostrand/
        dotnet build

    # Compile magic to dll with nostrand (self-hosting)
    - name: Generate new Magic assemblies
      run: |
        cd magic/
        rm -rf bootstrap/
        dotnet "../nostrand/bin/x64/Debug/net5.0/Nostrand.dll" "build/bootstrap"

    # Replace the old dlls in the bootstrap folder with the new ones and push to current branch
    - name: Commit the dll folder
      run: |
        cd magic/
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [ -n "$(git status --porcelain)" ]
        then
        git add bootstrap
        git commit -m "Generate the magic dll files in bootstrap folder"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: ./magic
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }} 
